# Generated by Django 5.1.4 on 2025-02-09 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0003_alter_message_options_alter_message_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-timestamp']},
        ),
    ]
