# Generated by Django 5.1.4 on 2025-03-08 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('liked', 'Like'), ('commented', 'Comment'), ('followed', 'Follow'), ('mentioned', 'Mention'), ('general', 'General'), ('follow_request', 'Follow request')], max_length=50),
        ),
    ]
