# Generated by Django 5.1.4 on 2025-01-22 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0005_alter_post_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posthashtag',
            name='hashtag',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Posts.hashtag'),
        ),
    ]
