# Generated by Django 5.1.4 on 2025-01-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0006_alter_posthashtag_hashtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='tag',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
