# Generated by Django 5.1.4 on 2025-01-22 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0007_alter_hashtag_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posthashtag',
            name='hashtag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Posts.hashtag'),
        ),
    ]
