# Generated by Django 5.1.4 on 2025-01-16 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stories', '0002_storycomment_storylike_storyview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='viewers',
        ),
    ]
