# Generated by Django 5.1.4 on 2025-03-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stories', '0003_remove_story_viewers'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10),
        ),
        migrations.AlterField(
            model_name='story',
            name='media_file',
            field=models.FileField(blank=True, upload_to='stories/'),
        ),
    ]
