# Generated by Django 5.1.4 on 2025-02-19 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0011_usersettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='dark_mode',
        ),
    ]
