# Generated by Django 5.1.4 on 2025-02-20 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0012_remove_usersettings_dark_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_images/default_user_profile_image.png', upload_to='profile_images/'),
        ),
    ]
