# Generated by Django 5.1.4 on 2025-02-21 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0015_user_auth_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(choices=[('email', 'Email'), ('google', 'Google'), ('facebook', 'Facebook'), ('github', 'GitHub')], default='email', max_length=20),
        ),
    ]
